/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SongInput = IDL.Record({
  'id' : IDL.Text,
  'bpm' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Float64,
  'difficulty' : IDL.Text,
  'artist' : IDL.Text,
});
export const Song = IDL.Record({
  'id' : IDL.Text,
  'bpm' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Float64,
  'difficulty' : IDL.Text,
  'artist' : IDL.Text,
});
export const Score = IDL.Record({
  'score' : IDL.Nat,
  'stars' : IDL.Nat,
  'timestamp' : IDL.Int,
  'playerName' : IDL.Text,
  'maxCombo' : IDL.Nat,
  'accuracy' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addSong' : IDL.Func([SongInput], [], []),
  'getAllSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
  'getSong' : IDL.Func([IDL.Text], [Song], ['query']),
  'getTopScores' : IDL.Func([IDL.Text], [IDL.Vec(Score)], ['query']),
  'submitScore' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Float64, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SongInput = IDL.Record({
    'id' : IDL.Text,
    'bpm' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Float64,
    'difficulty' : IDL.Text,
    'artist' : IDL.Text,
  });
  const Song = IDL.Record({
    'id' : IDL.Text,
    'bpm' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Float64,
    'difficulty' : IDL.Text,
    'artist' : IDL.Text,
  });
  const Score = IDL.Record({
    'score' : IDL.Nat,
    'stars' : IDL.Nat,
    'timestamp' : IDL.Int,
    'playerName' : IDL.Text,
    'maxCombo' : IDL.Nat,
    'accuracy' : IDL.Float64,
  });
  
  return IDL.Service({
    'addSong' : IDL.Func([SongInput], [], []),
    'getAllSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
    'getSong' : IDL.Func([IDL.Text], [Song], ['query']),
    'getTopScores' : IDL.Func([IDL.Text], [IDL.Vec(Score)], ['query']),
    'submitScore' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Float64, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };